# Generated by Django 5.0.14 on 2026-07-16 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def map_existing_roles(apps, schema_editor):
    Permission = apps.get_model("authentication", "Permission")
    Role = apps.get_model("authentication", "Role")
    User = apps.get_model("authentication", "User")

    permissions_data = [
        {"code": "settings", "label": "SETTINGS"},
        {"code": "warehouse", "label": "WAREHOUSE"},
        {"code": "pricing", "label": "PRICING"},
        {"code": "reports", "label": "REPORTS"},
        {"code": "users", "label": "USERS"},
        {"code": "orders", "label": "ORDERS"},
        {"code": "customers", "label": "CUSTOMERS"},
        {"code": "chat", "label": "CHAT"},
        {"code": "services", "label": "SERVICES"},
        {"code": "view_orders", "label": "VIEW ORDERS"},
    ]

    perms_dict = {}
    for perm_info in permissions_data:
        perm, _ = Permission.objects.get_or_create(
            code=perm_info["code"],
            defaults={"label": perm_info["label"]}
        )
        perms_dict[perm_info["code"]] = perm

    roles_data = [
        {
            "name": "Super Admin",
            "perms": ["settings", "warehouse", "pricing", "reports", "users", "orders", "customers", "chat", "services", "view_orders"],
        },
        {
            "name": "Admin",
            "perms": ["orders", "customers", "services", "reports", "chat"],
        },
        {
            "name": "Support Agent",
            "perms": ["chat", "view_orders"],
        },
    ]

    roles_dict = {}
    for role_info in roles_data:
        role_slug = slugify(role_info["name"])
        role, _ = Role.objects.get_or_create(
            name=role_info["name"],
            defaults={"slug": role_slug}
        )
        role.permissions.clear()
        for perm_code in role_info["perms"]:
            role.permissions.add(perms_dict[perm_code])
        roles_dict[role_info["name"]] = role

    for user in User.objects.all():
        old_val = getattr(user, "role_old", None)
        if old_val == "SUPER_ADMIN":
            user.role = roles_dict["Super Admin"]
        elif old_val == "ADMIN":
            user.role = roles_dict["Admin"]
        elif old_val == "SUPPORT_AGENT":
            user.role = roles_dict["Support Agent"]
        else:
            user.role = None
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='role_old',
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'permissions',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='authentication.permission')),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_initials',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='invite_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='invite_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='authentication.role'),
        ),
        migrations.RunPython(map_existing_roles, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='user',
            name='role_old',
        ),
    ]
