# Generated by Django 5.0.14 on 2026-07-16 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_permission_user_avatar_initials_user_invite_status_and_more'),
    ]

    operations = [
    ]
