# Generated by Django 5.0.14 on 2026-07-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('PUSH', 'Push Notification'), ('SMS', 'SMS'), ('EMAIL', 'Email')], default='PUSH', max_length=20),
        ),
    ]
